[package]
name = "spore-box"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-embed = "8.7.2"
wstd = "0.5.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
